# Generated by Django 4.2.29 on 2026-04-02 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0010_storesession_storeasset_ledgerentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('DAILY', 'Daily Expense'), ('MONTHLY', 'Monthly Expense')], default='DAILY', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('TRANSPORT', 'Transport'), ('MAINTENANCE', 'Maintenance'), ('MISC', 'Miscellaneous'), ('RENT', 'Rent'), ('ELECTRICITY', 'Electricity Bill'), ('SALARY', 'Salary'), ('PURCHASE', 'Stock Purchase'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='LoginAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_date', models.DateField(default=django.utils.timezone.now)),
                ('login_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], default='PRESENT', max_length=10)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='pos.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-login_date', '-login_time'],
                'indexes': [models.Index(fields=['login_date', 'store'], name='pos_loginat_login_d_f7f922_idx')],
            },
        ),
    ]
