# Generated by Django 4.2.29 on 2026-04-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_attendance_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wholesalecustomer',
            name='address',
            field=models.TextField(blank=True, help_text='Delivery / billing address'),
        ),
    ]
