# Generated by Django 4.2.29 on 2026-04-03 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0012_sale_customer_address_wholesalecustomer_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Cash Ledger, Bank Account, Supplier Dues', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(choices=[('#27a4d1', 'Ocean Blue'), ('#16a34a', 'Forest Green'), ('#dc2626', 'Ruby Red'), ('#7c3aed', 'Violet'), ('#d97706', 'Amber'), ('#0f172a', 'Midnight'), ('#db2777', 'Rose'), ('#0891b2', 'Cyan')], default='#27a4d1', max_length=10)),
                ('icon', models.CharField(default='fa-book', help_text='FontAwesome icon class e.g. fa-book', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_books', to='pos.store')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='ledger_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='pos.ledgerbook'),
        ),
    ]
