# Generated by Django 4.2.29 on 2026-04-06 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_ledgerbook_ledgerentry_ledger_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='pos.store'),
        ),
    ]
