# Generated by Django 4.2.29 on 2026-04-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_alter_employee_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='upi_id',
            field=models.CharField(blank=True, help_text='Store UPI ID for receiving payments', max_length=50),
        ),
    ]
