# Generated by Django 4.2.29 on 2026-05-04 10:13

from django.db import migrations, models
import pos.models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_store_code_wholesalecustomer_customer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeasset',
            name='bill_pdf',
            field=models.FileField(blank=True, null=True, upload_to=pos.models.asset_upload_path),
        ),
    ]
