# Generated by Django 4.2.29 on 2026-06-08 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_storeasset_bill_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='pos.product'),
        ),
        migrations.AddField(
            model_name='expense',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='transportation_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
