# Generated by Django 4.2.30 on 2026-06-08 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_expense_price_per_kg_expense_product_and_more'),
        ('pos', '0019_merge_20260504_1551'),
    ]

    operations = [
    ]
